### GROUPING DATA

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('sales_dataset_comprehensive.csv')

In [5]:
df.groupby('Region').agg({
    'Total_Amount': ['count', 'sum', 'mean', 'std',],
    'Quantity': 'sum',
    'Customer_Satisfaction': 'mean'
}).round(3)

        Total_Amount                              Quantity  \
               count        sum     mean      std      sum
Region
Central          990  892906.71  901.926  964.434     4104
East             962  888581.08  923.681  987.500     3863
North            993  915969.43  922.426  967.468     4153
South           1069  928820.60  868.869  893.158     4425
West             986  924700.88  937.831  989.387     4228

        Customer_Satisfaction
                         mean
Region
Central                 3.506
East                    3.501
North                   3.510
South                   3.495
West                    3.490

In [6]:
df.groupby(['Product', 'Region']).agg({
    'Total_Amount': ['count', 'sum', 'mean'],
    'Customer_Satisfaction': 'mean'
}).round(2)

                   Total_Amount                     Customer_Satisfaction
                          count        sum     mean                  mean
Product    Region
Desktop    Central           75  133266.67  1776.89                  3.45
           East              76  158093.48  2080.18                  3.57
           North             82  168531.84  2055.27                  3.48
           South             99  166752.29  1684.37                  3.44
           West              70  126971.09  1813.87                  3.53
Headphones Central           75   20031.35   267.08                  3.75
           East              86   20896.91   242.99                  3.46
           North             67   16824.85   251.12                  3.57
           South             95   24775.23   260.79                  3.44
           West              71   19591.94   275.94                  3.65
Keyboard   Central           83   42332.02   510.02                  3.46
           East              65   31762.72   488.66                  3.52
           North             86   42602.18   495.37                  3.51
           South             99   52567.11   530.98                  3.47
           West              73   39405.02   539.79                  3.43
Laptop     Central           92  239518.51  2603.46                  3.54
           East              83  220774.84  2659.94                  3.64
           North             92  223848.91  2433.14                  3.41
           South             89  214919.58  2414.83                  3.59
           West              97  254767.34  2626.47                  3.41
Monitor    Central           85   88162.13  1037.20                  3.33
           East              86   83139.71   966.74                  3.44
           North             84   85106.84  1013.18                  3.51
           South             84   74071.58   881.80                  3.55
           West              93   90517.39   973.31                  3.41
Mouse      Central           82   21923.27   267.36                  3.46
           East              83   19930.84   240.13                  3.46
           North             93   24105.84   259.20                  3.43
           South             80   21725.41   271.57                  3.44
           West              96   24929.68   259.68                  3.60
Phone      Central           95  133797.69  1408.40                  3.39
           East              79  126127.56  1596.55                  3.41
           North             84  128141.15  1525.49                  3.52
           South             80  119115.69  1488.95                  3.50
           West              82  122993.20  1499.92                  3.61
Printer    Central           81   49146.01   606.74                  3.70
           East              73   48195.56   660.21                  3.59
           North             74   50473.81   682.08                  3.46
           South             84   48857.73   581.64                  3.47
           West              91   57039.57   626.81                  3.42
Scanner    Central           71   32888.42   463.22                  3.53
           East              72   34049.73   472.91                  3.56
           North             77   33698.24   437.64                  3.41
           South             85   39757.84   467.74                  3.56
           West              73   35618.01   487.92                  3.44
Speaker    Central           91   24983.15   274.54                  3.51
           East              97   26873.22   277.04                  3.45
           North             93   30089.38   323.54                  3.68
           South             83   23743.71   286.07                  3.47
           West              76   26637.44   350.49                  3.63
Tablet     Central           80   89207.76  1115.10                  3.48
           East              82   99088.96  1208.40                  3.53
           North             76   93491.45  1230.15                  3.56
           South             96  120542.33  1255.65                  3.51
           West              83  107874.32  1299.69                  3.49
Webcam     Central           80   17649.73   220.62                  3.52
           East              80   19647.55   245.59                  3.41
           North             85   19054.94   224.18                  3.59
           South             95   21992.10   231.50                  3.49
           West              81   18355.88   226.62                  3.29